#!/bin/bash
sleep 1
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-wlr
killall xdg-desktop-portal
/nix/store/$(ls -a /nix/store | grep xdg-desktop-portal-hyprland | grep '^'d | awk '{print $9}' )/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/nix/store/$(ls -a /nix/store | grep xdg-desktop-portal | grep '^'d | awk '{print $9}' )/usr/lib/xdg-desktop-portal &
