#!/bin/bash
# Este script minimizara steam en vez de cerrarlo completamente
if [ "$(hyprctl activewindow -j | jq -r ".class")" = "Steam" ]; then
    xdotool getactivewindow windowunmap
else
    hyprctl dispatch killactive ""
fi
